export default [
  { title: "Assisted", value: "assisted"},
  { title: "Band", value: "band"},
  { title: "Barbell", value: "barbell"},
  { title: "Body Weight", value: "body weight"},
  { title: "Bosu Ball", value: "bosu ball"},
  { title: "Cable", value: "cable"},
  { title: "Dumbbell", value: "dumbbell"},
  { title: "Elliptical Machine", value: "elliptical machine"},
  { title: "Ez Barbell", value: "ez barbell"},
  { title: "Hammer", value: "hammer"}, 
  { title: "Kettlebell", value: "kettlebell"},
  { title: "Leverage Machine", value: "leverage machine"},
  { title: "Medicine Ball", value: "medicine ball"},
  { title: "Olympic Barbell", value: "olympic barbell"},
  { title: "Resistance Band", value: "resistance band"},
  { title: "Roller", value: "roller"},
  { title: "Rope", value: "rope"},
  { title: "Skierg Machine", value: "skierg machine"},
  { title: "Sled Machine", value: "sled machine"},
  { title: "Smith Machine", value: "smith machine"},
  { title: "Stability Ball", value: "stability ball"},
  { title: "Stationary Bpike", value: "stationary bike"},
  { title: "Stepmill Machine", value: "stepmill machine"},
  { title: "Tire", value: "tire"},
  { title: "Trap Bar", value: "trap bar"},
  { title: "Upper Body Ergometer", value: "upper body ergometer"},
  { title: "Weighted", value: "weighted"},
  { title: "Wheel Roller", value: "wheel roller"}
]